name = input("Please enter your name: ")
age = input("Please enter your age: ")
house_number = input("Please enter your house number: ")
street_name = input("Please enter your street name: ")
print(" ")
print(f"This is {name.capitalize()}. They are {age} years old and live at {house_number} {street_name}.")