 # Am I missing something from this task because it seems extremely easy...
 
# I wrote about 75% of the world's countries into this dictionary but I'm crunched for time today so I'll update this list with other countries later.

countryMap = {
        'Afghanistan':	'Kabul',
        'Albania':	'Tirana',
        'Algeria':	'Algiers',
        'Andorra'	:'Andorra la Vella',
        'Angola':	'Luanda',
        'Antigua and Barbuda':	'Saint Johns',
        'Argentina':	'Buenos Aires',
        'Armenia':	'Yerevan',
        'Australia':	'Canberra',
        'Austria':	'Vienna',
        'Azerbaijan':	'Baku',
        'Bahamas'	:'Nassau',
        'Bahrain'	:'Manama',
        'Bangladesh'	:'Dhaka',
        'Barbados'	:'Bridgetown',
        'Belarus'	:'Minsk',
        'Belgium':	'Brussels',
        'Belize'	:'Belmopan',
        'Benin':	'Porto-Novo',
        'Bhutan'	:'Thimphu',
        'Bolivia':	'La Paz',
        'Bosnia and Herzegovina'	:'Sarajevo',
        'Botswana'	:'Gaborone',
        'Brazil'	:'Brasilia',
        'Brunei':	'Bandar Seri Begawan',
        'Bulgaria'	:'Sofia',
        'Burkina Faso':	'Ouagadougou',
        'Burundi':	'Gitega',
        'Cabo Verde'	:'Praia',
        'Cambodia'	:'Phnom Penh',
        'Cameroon':	'Yaounde',
        'Canada'	:'Ottawa',
        'Central African Republic':	'Bangui',
        'Chad'	:'NDjamena',
        'Chile'	:'Santiago',
        'China'	:'Beijing',
        'Colombia'	:'Bogotá',
        'Comoros'	:'Moroni',
        'Democratic Republic of the Congo':	'Kinshasa',
        'Republic of the Congo':	'Brazzaville',
        'Costa Rica'	:'San Jose',
        'Cote dIvoire'	:'Yamoussoukro',
        'Croatia'	:'Zagreb',
        'Cuba'	:'Havana',
        'Cyprus'	:'Nicosia',
        'Czechia':	'Prague',
        'Nepal':	'Kathmandu',
        'Netherlands'	:'Amsterdam',
        'New Zealand':	'Wellington',
        'Nicaragua':	'Managua',
        'Niger':	'Niamey',
        'Nigeria':	'Abuja',
        'North Korea':	'Pyongyang',
        'North Macedonia':	'Skopje',
        'Norway'	:'Oslo',
        'Oman'	:'Muscat',
        'Pakistan'	:'Islamabad',
        'Palau'	:'Ngerulmud',
        'Palestine':	'Jerusalem',
        'Panama':	'Panama City',
        'Papua New Guinea'	:'Port Moresby',
        'Paraguay'	:'Asunción',
        'Peru'	:'Lima',
        'Philippines'	:'Manila',
        'Poland'	:'Warsaw',
        'Portugal'	:'Lisbon',
        'Qatar':	'Doha',
        'Romania'	:'Bucharest',
        'Russia'	:'Moscow',
        'Rwanda'	:'Kigali',
        'Saint Kitts and Nevis':	'Basseterre',
        'Saint Lucia':	'Castries',
        'Saint Vincent and the Grenadines'	:'Kingstown',
        'Samoa'	:'Apia',
        'San Marino':	'San Marino',
        'Sao Tome and Principe'	:'São Tomé',
        'Saudi Arabia'	:'Riyadh',
        'Senegal':	'Dakar',
        'Serbia'	:'Belgrade',
        'Seychelles'	:'Victoria',
        'Sierra Leone'	:'Freetown',
        'Singapore'	:'Singapore',
        'Slovakia'	:'Bratislava',
        'Slovenia':	'Ljubljana',
        'Solomon Islands'	:'Honiara',
        'Somalia':	'Mogadishu',
        'South Africa'	:'Pretoria',
        'South Korea'	:'Seoul',
        'South Sudan'	:'Juba',
        'Spain':	'Madrid',
        'Sri Lanka':	'Sri Jayawardenepura Kotte',
        'Sudan'	:'Khartoum',
        'Suriname'	:'Paramaribo',
        'Sweden'	:'Stockholm',
        'Switzerland'	:'Bern',
        'Syria'	:'Damascus',
        'Taiwan'	:'Taipei',
        'Tajikistan'	:'Dushanbe',
        'Tanzania'	:'Dodoma',
        'Thailand'	:'Bangkok',
        'Timor-Leste':	'Dili',
        'Togo':	'Lomé',
        'Tonga':	'Nukualofa',
        'Trinidad and Tobago'	:'Port of Spain',
        'Tunisia'	:'Tunis',
        'Turkey'	:'Ankara',
        'Turkmenistan'	:'Ashgabat',
        'Tuvalu'	:'Funafuti',
        'Uganda'	:'Kampala',
        'Ukraine':	'Kyiv',
        'United Arab Emirates'	:'Abu Dhabi',
        'United Kingdom':	'London',
        'United States of America':	'Washington, D.C.',
        'Uruguay'	:'Montevideo',
        'Uzbekistan'	:'Tashkent',
        'Vanuatu'	:'Port Vila',
        'Vatican City': 'Vatican City',
        'Venezuela'	:'Caracas',
        'Vietnam'	:'Hanoi',
        'Yemen':	'Sanaa',
        'Zambia'	:'Lusaka',
        'Zimbabwe'	:'Harare',
        }
print(countryMap['Zambia'])

 # Thank you to Chris Smit for all the helpful feedback!

 # I've recalled a single value with a key from my dictionary, indented, and split up my comments a bit.