# -*- coding: utf-8 -*-
"""task_2

Automatically generated by Colaboratory.

Original file is located at
https://colab.research.google.com/drive/1tlxZ9KYxZawfhLibCSKvdWsc0jCeSFHU
"""

 # I got a lot of great information from this youtube video going over the basics of Spacy:
 #https://www.youtube.com/watch?v=dIUTsFT2MeQ
import spacy # initialize program
nlp = spacy.load('en_core_web_sm') # load English

list=[] # create an empty list
with open("movies.txt", "r") as f:
  for line in f.readlines():
    doc = nlp(line) # tokenize 
    print(doc)
    list.append(doc) # append to list
print("\n")

 # Input movie variable that we are comparing
similarity = '''Will he save
their world or destroy it? When the Hulk becomes too dangerous for the
Earth, the Illuminati trick Hulk into a shuttle and launch him into space to a
planet where the Hulk can live in peace. Unfortunately, Hulk land on the
planet Sakaar where he is sold into slavery and trained as a gladiator.'''

check_list = [] # create empty list
for entry in list: # find similarity scores for each movie
  check = nlp(entry).similarity(nlp(similarity))
  print(str(entry) + ":" + str(check)) # print out each entry and score
  print("\n")
  check_list.append(check) # add to list
check_list.sort(reverse=True) # sort list

for entry in list: # find highest similarity score
  check = nlp(entry).similarity(nlp(similarity))
  if check == check_list[0]:
     print(f'\nWe recommend "{entry}" because it is most similar to your last watched movie.') 
     # give recommendation

'''
This assignment was really fun actually! I think I completed all of the components. If I am missing something, please let me know.

Thank you!
'''