item_one = input("Hello! Think fast... What's your favorite food? ")
print(" ")
print("Eww... Really? That's what you came up with...?")
print(" ")
item_two = input(f"Think really hard now... Pick a food. ANYTHING besides {item_one}: ")
print(" ")
print(f"Well by golly, gee wiz. You're a nasty piece of work. You know that?? {item_one.capitalize()} AND {item_two.lower()}. Jesus...")
print(" ")
item_three = input("Okay... this is your last chance. One more choice like those and I'll destroy your hard drive... I'm begging you! List ONE GOOD FOOD: ")
print(" ")
print(f'Oh! ... Yum! I love {item_three}.')
print(" ")
print(" ")
print('Okay. Here is your ALMOST entirely disgusting menu: ' )
print(item_one)
print(item_two)
print(item_three)